### PR TITLE
Add passwordfill support for secure entry fields

### PR DESCRIPTION
**Pull request by nstrauss**
Using the secure option with text fields and 3rd party password managers like 1Password, an empty shadow could appear when focusing the field. @bartreardon confirmed this was due to the `.password` modifier with `SecureField` and `textContentType`. The intention is for the macOS password manager to auto-fill or create a password as necessary, but 3rd party managers (at least 1Password) and SwiftUI don't seem to get along.

This PR fixes empty shadow rendering by adding support for a new `passwordfill` option in text fields. It can be used by specifying `passwordfill` in dialog arguments. For example...

```
--textfield 'Password',secure,passwordfill,required
```

By default password fill is turned off. I don't think folks need/want this in most scenarios where users are prompted for password input. They would enter a password manually. However, I wanted to keep the option available as to not introduce feature regressions. Please feel free to provide feedback or make edits yourself to make this ready to merge. Thank you!

shadow

### CODE REVIEW

**Comment by bartreardon** [comment]
@nstrauss I've switched from the main branch to dev but there are conflicts present, can I get you to resolve those?

**Comment by nstrauss** [comment]
@bartreardon Thanks. I'll work from dev if I contribute in the future. Alphabetized things cause I had to. Otherwise I was able to build locally and test as working.

**Comment by bartreardon** [comment]
ta - btw, you might want to add the following to your `.git/info/exclude` 

```
*.xcuserstate
*.resolved
xcuserdata
xcsharedata
```

**Comment by bartreardon** [comment]
re https://github.com/bartreardon/swiftDialog/pull/154/commits/7473a92966cd0bb1097e87e9717a6d38d411228e - no-one knows 😛

**Comment by nstrauss** [comment]
😅 Clearly I don't work in Xcode a lot. Happy to contribute in small ways where I can.

**Pull request merged**
